# Desarrollo con hot reload
FROM node:20-alpine

WORKDIR /app

RUN npm install -g nodemon ts-node

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "ts-node", "src/index.ts"]
